Skeleton for type inference of PHP via the PIL
Summary:
Just to make sure we can really piss of Haiping, let's work on
type inference :)

This is just the skeleton. There are lots of work to get this working
but I think it's doable in a few weeks now that the PIL is almost
done.

PS: if you read this Haiping I was joking (well actually only half-joking,
I really want to implement type inference of PHP in pfff but for
some needs in static analysis related to security).

Test Plan:
./scheck -type_inference tests/php/type_inference/foo.php
which right now just output:
File contain constructions not supported by the PIL; bailing out
Fatal error: exception Common.Todo
Raised at file "pil_build.ml", line 871, characters 8-12
Called from file "main_scheck.ml", line 250, characters 14-42
Re-raised at file "main_scheck.ml", line 267, characters 10-13

because I didn't finish it yet the AST -> PIL conversion function
in pil_build.ml

DiffCamp Revision: 170094
Reviewed By: asuhan
CC: dougli, iproctor, pad, asuhan
Revert Plan:
OK